version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - C:\Code\DevSecOps\app:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: